### PR TITLE
move allowOutsideScroll into properties block

### PR DESCRIPTION
**Pull request by danbeam**
it probably doesn't work otherwise?

### CODE REVIEW

**Comment by valdrinkoshi** [comment]
wow, mea culpa, how didn't i see that in https://github.com/PolymerElements/paper-menu-button/pull/67? 😞 
@danbeam, could you add a simple unit test just to check if the property does get propagated to the internal dropdown?

**Comment by danbeam** [comment]
i added a _very simple_ unit test.

i don't really see the value in another fixture with a `allow-outside-scroll` boolean HTML attribute.  because that's really just ... testing bool HTML arguments... but I'll add one if you want!

**Comment by valdrinkoshi** [comment]
LGTM 👍 
@danbeam yeah I agree, no need to add a new fixture for this, toggling the property is more than enough 👌 Thanks!

**Pull request merged**
