### PR TITLE
Add allow-outside-scroll property - Rebased (#62)

### PR DESCRIPTION
**Pull request by jwwisgerhof**
As PR #62 is currently not attended to (11 days since last comment), I went ahead and did a quick rebase.

### CODE REVIEW

**Comment by jwwisgerhof** [comment]
Signed CLA.

**Comment by jwwisgerhof** [comment]
@mattppp Authored the commit and added his CLA in PR #62. His code is unchanged.

**Comment by mattppp** [comment]
Thanks @jwwisgerhof! Much appreciated.

**Comment by jwwisgerhof** [comment]
I did author those commits - with the permission of Matt Privman (who
acknowledged).

Regards,

Jan-Willem Wisgerhof
04 88198485

**Comment by mattppp** [comment]
@cdata Can we get this merged in?

**Comment by TimvdLippe** [comment]
Ping. I just hit the issue of not finding the property, because it was not propagated back to `paper-menu-button`.

**Comment by valdrinkoshi** [comment]
@jwwisgerhof would you mind re-basing this again? last time, promise! 😁

**Comment by jwwisgerhof** [comment]
@valdrinkoshi Can you have a look at why the build is failing? Seems to not be an issue with the code but a test setup issue instead.

> Error: Missing /home/travis/.nvm/versions/node/v6.2.2/lib/node_modules/web-component-tester/node_modules/selenium-standalone/.selenium/selenium-server/2.53.1-server.jar

**Comment by valdrinkoshi** [comment]
Actually all the repos are failing with that error, even on master. Waiting for @azakus to give us more infos on this.
I can try this locally on Monday and merge it if all looks good.

**Pull request merged**
