### PR TITLE
allow configuring restore-focus-on-close

### PR DESCRIPTION
**Pull request by danbeam**
/cc @cdata

### CODE REVIEW

**Comment by danbeam** [comment]
copy pasta'd the test from https://github.com/PolymerElements/paper-menu-button/pull/95

**Comment by valdrinkoshi** [comment]
LGTM 👌

**Comment by dukhanov** [comment]
Hi, regarding the documentation of boolean [attributes](https://www.w3.org/TR/2008/WD-html5-20080610/semantics.html#boolean), boolean attributes: 

> The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.

But the default value of `restore-focus-on-close` is true, this may mislead.

**Pull request merged**
